FORMAT: 1A
HOST: http://www.google.com

# Notes API
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

## Programacao do Cinema [/cinema/programacao]
### Lista a programação do cinema [GET]
+ Response 200 (application/json)

        [{
            "filme": {
                "id": 169,
                "titulo": "Frankenstein - Entre Anjos e Demonios",
                "titulooriginal": "Frankenstein - Entre Anjos e Demonios",
                "sinopse": "Versão moderna da história do cientista Frankenstein e de seu monstro. Desta vez, a criatura participa de uma longa e sangrenta batalha entre dois grupos que se opõem há séculos.",
                "palavraschave": null,
                "duracao": 92,
                "site": null,
                "trailer": null,
                "censura": "12",
                "cartaz": "cine1389897954_492.jpg",
                "imagem": null,
                "status": 1,
                "idlanguage": "pt",
                "estreia": 2,
                "preestreia": 2,
                "dias": [
                    "Seg",
                    "Ter",
                    "Qua",
                    "Qui",
                    "Sex",
                    "Sáb",
                    "Dom"
                    ],
                "opcoes": [
                    "3D Dublado",
                    "3D Legendado"
                ]
            },
            "generos": [
                {
                "id": 8,
                "nome": "Terror",
                "idlanguage": "pt"
                }
            ],
            "opcoes": {
                "1064": {
                    "programacao": {
                        "id": 1064,
                        "nome": "Frankenstein - Entre Anjos e Demonios",
                        "dimensao": "3D",
                        "legenda": "Dublado",
                        "datahoraentrada": "31/01/2014 00:01:00",
                        "datahorasaida": "06/02/2014 00:00:00",
                        "estreia": 2,
                        "preestreia": 2,
                        "linkcompraringresso": null,
                        "ordem": 1,
                        "status": 1,
                        "idlanguage": "pt"
                    },
                    "sessoes": {
                        "2027": {
                            "dias": "Diariamente",
                            "horarios": {
                                "4572": {
                                    "sala": "6",
                                    "hora": "13:10"
                                },
                                "4573": {
                                    "sala": "6",
                                    "hora": "15:30"
                                }
                            }
                        }
                    }
                },
                "1065": {
                    "programacao": {
                        "id": 1065,
                        "nome": "Frankenstein - Entre Anjos e Demonios",
                        "dimensao": "3D",
                        "legenda": "Legendado",
                        "datahoraentrada": "31/01/2014 00:01:00",
                        "datahorasaida": "06/02/2014 00:00:00",
                        "estreia": 2,
                        "preestreia": 2,
                        "linkcompraringresso": null,
                        "ordem": 2,
                        "status": 1,
                        "idlanguage": "pt"
                    },
                    "sessoes": {
                        "2028": {
                            "dias": "Diariamente",
                            "horarios": {
                                "4574": {
                                    "sala": "6",
                                    "hora": "17:50"
                                },
                                "4575": {
                                    "sala": "6",
                                    "hora": "20:10"
                                },
                                "4576": {
                                    "sala": "6",
                                    "hora": "22:30"
                                }
                            }
                        }
                    }
                }
            }
        }]

## Informacoes do Cinema [/cinema/informacao]
### Lista as informações do cinema [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "empresa": " Cinemark",
            "chamada": null,
            "descricao": "Confira aqui a programação do Cinemark do Shopping Vitória. São 8 amplas salas, com muitas atrações para você.",
            "logo": "cine_informacao_1391105950_470.jpg",
            "imagem": null,
            "video": null,
            "link": "http://www.cinemark.com.br",
            "horariofuncionamento": null,
            "valores": " ",
            "contato": "Maiores informações no site <a href="http://www.cinemark.com.br" target="_blank" >www.cinemark.com.br</a>.",
            "status": 1,
            "idlanguage": "pt"
        }]
        
## Informacoes do Filme [/cinema/filme/codFilme/{codFilme}]
Obtem um filme especifico com todas as suas informacoes

+ Parameters
    + codFilme (required, number, `1`) ... Numeric `codFilme` of the Note to perform action with. Has example value.

### Obtem as informações de um filme específico [GET] 
+ Response 200 (application/json) 
        [
        "filme": {
            "id": 181,
            "titulo": "Até Que a Sorte Nos Separe 2",
            "titulooriginal": "Até Que a Sorte Nos Separe 2",
            "sinopse": "Juntos novamente, Tino e Jane mais uma vez estão em dificuldades financeiras. O saldo bancário do casal é salvo graças ao inesperado falecimento de tio Olavinho, que deixou para eles uma herança de R$ 50 milhões. Como o último desejo do tio foi que suas cinzas sejam jogadas no Grand Canyon, Tino e família aproveitam a viagem para dar uma esticada até Las Vegas.",
            "palavraschave": "",
            "duracao": 102,
            "site": "",
            "trailer": "",
            "censura": "10",
            "cartaz": "cine_filme_1387814390_367.jpg",
            "imagem": null,
            "status": 1,
            "idlanguage": "pt",
            "estreia": 2,
            "preestreia": 2
        }]
    


### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
